version: '2'
services:
  web:
    build: .
    command: npm start 
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3333:3333"
    links:
      - mongo:mongo
    networks:
      - connector
    
    environment:
      MONGODB_URI: mongodb://mongo:27017

  mongo:
    image: mvertes/alpine-mongo
    environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
    expose:
      - 27017
    ports:
      - 27017:27017
    networks: 
      - connector
    command: mongod --port 27017 --bind_ip_all

networks:
  connector:  